sudo: required
services:
  - docker

before_install: 
  - docker build -t KarthikSamaganam550/docker_react_repo -f Dockerfile.dev
  
script:
  - docker run KarthikSamaganam550/docker_react_repo npm run test -- -- coverage
